#!/usr/bin/env bash

if [ -z "$2" ]
then
  limit=100
else
  limit=$2
fi
echo "running task $limit times"
start=$(date +%s.%N)
for i in $( seq $limit )
do
  /usr/bin/env python3 run.py $1 > /dev/null 2>&1
done

end=$(date +%s.%N)
dur=$(echo "$end - $start" | bc)
echo $dur
